<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>GcodeRecovery.App</RootNamespace>
    <AssemblyName>GcodeRecovery</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NoWarn>$(NoWarn);CS0618</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.22" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../GcodeRecovery.Core/GcodeRecovery.Core.csproj" />
    <ProjectReference Include="../GcodeRecovery.Printers/GcodeRecovery.Printers.csproj" />
    <ProjectReference Include="../GcodeRecovery.Telemetry/GcodeRecovery.Telemetry.csproj" />
  </ItemGroup>
</Project>
