using System.Globalization;

namespace GcodeRecovery.Core.Tests;

/// <summary>Generates small, realistic G-code programs: a solid block printed with raster lines.</summary>
internal static class SyntheticGcode
{
    public enum Style { Bambu, Orca, NoMarkers }

    public static List<string> SolidBlock(
        int layers = 50, double layerHeight = 0.2, double firstLayer = 0.2,
        double x0 = 100, double y0 = 100, double size = 20, bool absoluteE = false, Style style = Style.Bambu)
    {
        var inv = CultureInfo.InvariantCulture;
        var lines = new List<string>
        {
            "; HEADER_BLOCK_START",
            style == Style.Bambu ? "; BambuStudio 02.00.00.00" : "; generated by OrcaSlicer 2.2.0",
            "; HEADER_BLOCK_END",
            "G90",
            absoluteE ? "M82" : "M83",
            "M140 S60",
            "M104 S220",
            "M190 S60",
            "M109 S220",
            "G28",
            "G1 Z5 F600",
            "G1 X10 Y10 F6000",
            "G1 Z0.3",
            absoluteE ? "G1 X60 E5 F1500" : "G1 X60 E5 F1500", // purge line, before first layer
            "M106 P1 S0",
        };
        var e = absoluteE ? 5.0 : 0.0;
        var z = 0.0;
        for (var l = 0; l < layers; l++)
        {
            var h = l == 0 ? firstLayer : layerHeight;
            z = Math.Round(z + h, 4);
            switch (style)
            {
                case Style.Bambu:
                    lines.Add("; CHANGE_LAYER");
                    lines.Add($"; Z_HEIGHT: {z.ToString(inv)}");
                    lines.Add($"; LAYER_HEIGHT: {h.ToString(inv)}");
                    lines.Add("; LINE_WIDTH: 0.42");
                    break;
                case Style.Orca:
                    lines.Add(";LAYER_CHANGE");
                    lines.Add($";Z:{z.ToString(inv)}");
                    lines.Add($";HEIGHT:{h.ToString(inv)}");
                    lines.Add(";WIDTH:0.42");
                    break;
            }
            if (l == 1) lines.Add("M106 P1 S255");
            lines.Add($"G1 Z{(z + 0.4).ToString(inv)} F600"); // hop
            lines.Add($"G1 X{x0.ToString(inv)} Y{y0.ToString(inv)} F12000");
            lines.Add($"G1 Z{z.ToString(inv)}");
            var y = y0;
            var dir = 1;
            while (y <= y0 + size + 1e-9)
            {
                var xs = dir > 0 ? x0 : x0 + size;
                var xe = dir > 0 ? x0 + size : x0;
                lines.Add($"G1 X{xs.ToString(inv)} Y{y.ToString(inv)}");
                var amount = 0.8;
                e += amount;
                lines.Add($"G1 X{xe.ToString(inv)} Y{y.ToString(inv)} E{(absoluteE ? e : amount).ToString("0.#####", inv)} F3000");
                y = Math.Round(y + 0.4, 4);
                dir = -dir;
            }
        }
        lines.Add("M104 S0");
        lines.Add("M140 S0");
        lines.Add("; CONFIG_BLOCK_START");
        lines.Add($"; {(style == Style.Bambu ? "initial_layer_print_height" : "first_layer_height")} = {firstLayer.ToString(inv)}");
        lines.Add("; printer_model = Bambu Lab P1S");
        lines.Add("; CONFIG_BLOCK_END");
        return lines;
    }
}
