using System.Globalization;
using GcodeRecovery.Core.Gcode;

namespace GcodeRecovery.Core.Recovery;

public sealed class GenerationResult
{
    public required List<string> Lines { get; init; }
    public List<string> Warnings { get; } = new();
    public int DiscardedLines { get; init; }
    public int KeptLines { get; init; }
}

/// <summary>
/// Builds the recovery program:
/// <list type="number">
/// <item>header + summary comments</item>
/// <item>preparation (bed hot, nozzle cold, X/Y homed, provisional Z)</item>
/// <item>tool selection and re-activation of the original bed mesh (no new leveling)</item>
/// <item>cold load-cell touch-down on the part, contact becomes the Z reference</item>
/// <item>heat, purge and wipe away from the part</item>
/// <item>state restore (temperatures, fans, extrusion mode, extruder position)</item>
/// <item>the original G-code from the first line of the resume layer onwards, with Z remapped</item>
/// </list>
/// </summary>
public static class ResumeGenerator
{
    /// <summary>Minimum distance between the Z-home touch spot and the part.</summary>
    public const double MinZHomeClearanceMm = 8;

    public static GenerationResult Generate(GcodeModel model, RecoveryPlan plan, PrinterProfile profile, bool touchTestOnly = false)
    {
        var o = plan.Options;
        var state = plan.ResumeLayer.StateAtStart;
        var unknown = new SortedSet<string>(StringComparer.OrdinalIgnoreCase);
        var values = BuildValues(model, plan, profile, state);
        var output = new List<string>(touchTestOnly ? 200 : model.Lines.Count - plan.ResumeLayer.StartLine + 400);

        // Keep the slicer header block (thumbnails, metadata the printer UI may read).
        if (!touchTestOnly)
            for (var i = 0; i < model.HeaderLineCount; i++) output.Add(model.Lines[i]);

        output.Add("; ==================================================================");
        output.Add(touchTestOnly ? "; Gcode Recovery: TOUCH TEST ONLY (no printing)" : "; Gcode Recovery: resume program");
        output.Add($"; Printer profile        : {profile.Name}");
        output.Add($"; Touched surface        : layer {plan.SurfaceLayer.Index + 1} (top at Z {F(plan.SurfaceLayer.Z)} mm in the original file)");
        output.Add($"; Resume from            : layer {plan.ResumeLayer.Index + 1} of {model.Layers.Count} (original Z {F(plan.ResumeLayer.Z)} mm), reprinted from its first line");
        output.Add($"; Touch point            : X {F(plan.TouchX)}  Y {F(plan.TouchY)}");
        output.Add($"; Z frame                : {(o.ZFrame == ZFrameMode.ShiftToContactZero ? "contact = Z0, remaining Z shifted by -" + F(plan.ZShift) : "original Z kept, contact = Z " + F(plan.ContactZ))}");
        output.Add($"; Resume layer nozzle Z  : {F(plan.ResumeZ)} (gap {F(plan.ResumeGap)} mm above the touched surface)");
        output.Add($"; First-layer height     : {F(model.FirstLayerHeight)} mm ({(model.FirstLayerHeightFromSettings ? "from slicer settings" : "from first layer Z")})");
        output.Add("; Generated by Gcode Recovery - https://github.com/ddann/gcode-recovery");
        output.Add("; ==================================================================");

        var homeZ = o.HomeZAtClearSpot && !string.IsNullOrWhiteSpace(profile.ZHomePrepareTemplate);
        if (homeZ)
        {
            var clearance = PartClearance.DistanceToPart(model, plan.SurfaceLayer.Index, profile.ZHomeX, profile.ZHomeY);
            if (clearance < MinZHomeClearanceMm)
                throw new InvalidOperationException(
                    $"Z cannot be homed at X{F(profile.ZHomeX)} Y{F(profile.ZHomeY)}: the part is only {F(Math.Max(0, clearance))} mm away.");
        }
        Append(output, homeZ ? profile.ZHomePrepareTemplate : profile.PrepareTemplate, values, unknown);
        if (state.Tool >= 0 && !string.IsNullOrWhiteSpace(profile.ToolSelectTemplate))
            Append(output, profile.ToolSelectTemplate, values, unknown);
        Append(output, profile.LevelingTemplate, values, unknown);
        Append(output, profile.ProbeTemplate, values, unknown);

        if (touchTestOnly)
        {
            Append(output, profile.TouchTestEndTemplate, values, unknown);
            return Finish(output, unknown, 0, 0);
        }

        Append(output, profile.PurgeTemplate, values, unknown);
        AppendRestore(output, plan, state, profile.PrimeAfterPurgeMm);

        var kept = 0;
        foreach (var line in RemapZ(model, plan))
        {
            output.Add(line);
            kept++;
        }
        var result = Finish(output, unknown, plan.ResumeLayer.StartLine - model.HeaderLineCount, kept);
        if (model.LayerDetection == "Z")
            result.Warnings.Add("The G-code has no slicer layer markers; layers were detected from Z motion. Review the resume layer carefully.");
        return result;
    }

    private static GenerationResult Finish(List<string> output, SortedSet<string> unknown, int discarded, int kept)
    {
        var result = new GenerationResult { Lines = output, DiscardedLines = Math.Max(0, discarded), KeptLines = kept };
        if (unknown.Count > 0)
            result.Warnings.Add("Unknown template placeholders left unchanged: " + string.Join(", ", unknown.Select(u => "{" + u + "}")));
        return result;
    }

    private static void Append(List<string> output, string template, IReadOnlyDictionary<string, string> values, ICollection<string> unknown)
    {
        output.AddRange(TemplateEngine.Render(template, values, unknown));
    }

    private static void AppendRestore(List<string> output, RecoveryPlan plan, MachineState state, double primeMm)
    {
        output.Add("; --- Straight from the freshly wiped nozzle to the resume point, then print ---");
        foreach (var fan in state.Fans.OrderBy(f => f.Key).Select(f => f.Value)) output.Add(fan);
        // G90 first: on Marlin-style firmware G90 also resets the extruder to absolute mode.
        output.Add("G90");
        output.Add($"G1 Z{F(plan.SafeZ)} F600");
        output.Add($"G1 X{F(state.X)} Y{F(state.Y)} F{F(Math.Max(plan.Options.TravelFeed, 12000))}");
        output.Add($"G1 Z{F(plan.ResumeZ)} F600");
        if (primeMm > 0)
        {
            output.Add("M83");
            output.Add($"G1 E{primeMm.ToString("0.###", CultureInfo.InvariantCulture)} F1800 ; re-prime what the cleaner retracted");
        }
        output.Add(state.AbsoluteE ? "M82" : "M83");
        output.Add(state.AbsoluteE ? $"G92 E{state.E.ToString("0.#####", CultureInfo.InvariantCulture)}" : "G92 E0");
        output.Add($"G1 F{F(state.Feedrate)}");
        if (!state.AbsoluteXyz) output.Add("G91");
        output.Add($"; --- Original G-code from layer {plan.ResumeLayer.Index + 1} ---");
    }

    /// <summary>Copies the remaining program, subtracting the Z shift from every absolute Z (G0-G3, G92).</summary>
    public static IEnumerable<string> RemapZ(GcodeModel model, RecoveryPlan plan)
    {
        var absolute = plan.ResumeLayer.StateAtStart.AbsoluteXyz;
        var shift = plan.ZShift;
        for (var i = plan.ResumeLayer.StartLine; i < model.Lines.Count; i++)
        {
            var raw = model.Lines[i];
            if (shift == 0 || raw.Length == 0 || raw[0] == ';')
            {
                yield return raw;
                continue;
            }
            var line = GcodeLine.Parse(raw);
            switch (line.Command)
            {
                case "G90": absolute = true; break;
                case "G91": absolute = false; break;
            }
            if (line.TryGet('Z', out var z) && ((line.IsMove && absolute) || line.Command == "G92"))
                yield return line.WithParam('Z', z - shift);
            else
                yield return raw;
        }
    }

    private static Dictionary<string, string> BuildValues(GcodeModel model, RecoveryPlan plan, PrinterProfile profile, MachineState state)
    {
        var o = plan.Options;
        var (purgeX, purgeY, wipe) = PurgePosition(model, plan, profile);
        var nozzle = state.NozzleTemp > 0 ? state.NozzleTemp : model.Layers.Max(l => l.StateAtStart.NozzleTemp);
        return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            ["bed_temp"] = F(state.BedTemp),
            ["nozzle_temp"] = F(nozzle),
            ["probe_nozzle_temp"] = F(o.ProbeNozzleTemp),
            ["probe_nozzle_max_temp"] = F(o.ProbeNozzleMaxTemp),
            ["cooldown_s"] = o.CooldownSeconds.ToString(CultureInfo.InvariantCulture),
            ["lift"] = F(o.LiftBeforeHomingMm),
            ["probe_travel"] = F(o.ProbeTravelMm),
            ["probe_speed"] = F(o.ProbeSpeedMmS),
            ["probe_feed"] = F(o.ProbeSpeedMmS * 60),
            ["travel_feed"] = F(o.TravelFeed),
            ["touch_x"] = F(plan.TouchX),
            ["touch_y"] = F(plan.TouchY),
            ["contact_z"] = F(plan.ContactZCompensated),
            ["safe_z"] = F(plan.SafeZ),
            // Absolute height clearly above the part (only meaningful after a real Z home): the surface layer
            // plus the search uncertainty plus the clearance.
            ["part_clear_z"] = F(plan.SurfaceLayer.Z + 1.0 + o.ClearanceMm),
            ["zhome_x"] = F(profile.ZHomeX),
            ["zhome_y"] = F(profile.ZHomeY),
            ["resume_z"] = F(plan.ResumeZ),
            ["purge_x"] = F(purgeX),
            ["purge_y"] = F(purgeY),
            ["wipe_dx"] = F(wipe),
            ["wipe_dx_back"] = F(-wipe),
            ["purge_length"] = F(o.PurgeLengthMm),
            ["prime_length"] = F(profile.PrimeAfterPurgeMm),
            ["tool"] = Math.Max(0, state.Tool).ToString(CultureInfo.InvariantCulture),
            ["layer"] = (plan.ResumeLayer.Index + 1).ToString(CultureInfo.InvariantCulture),
        };
    }

    /// <summary>Profile purge position, or the bed corner (10 mm inset) farthest from the part's footprint.</summary>
    public static (double X, double Y, double WipeDx) PurgePosition(GcodeModel model, RecoveryPlan plan, PrinterProfile profile)
    {
        const double inset = 10;
        if (profile.PurgeX is { } px && profile.PurgeY is { } py)
            return (px, py, px < profile.BedWidth / 2 ? 10 : -10);

        var segs = model.Layers.Where(l => l.Index <= plan.ResumeLayer.Index).SelectMany(l => l.Segments);
        double minX = double.MaxValue, minY = double.MaxValue, maxX = double.MinValue, maxY = double.MinValue;
        foreach (var s in segs)
        {
            minX = Math.Min(minX, Math.Min(s.X1, s.X2)); maxX = Math.Max(maxX, Math.Max(s.X1, s.X2));
            minY = Math.Min(minY, Math.Min(s.Y1, s.Y2)); maxY = Math.Max(maxY, Math.Max(s.Y1, s.Y2));
        }
        var cx = (minX + maxX) / 2;
        var cy = (minY + maxY) / 2;
        (double X, double Y)[] corners =
        [
            (inset, inset), (profile.BedWidth - inset, inset),
            (inset, profile.BedDepth - inset), (profile.BedWidth - inset, profile.BedDepth - inset),
        ];
        var best = corners.OrderByDescending(c => Math.Pow(c.X - cx, 2) + Math.Pow(c.Y - cy, 2)).First();
        return (best.X, best.Y, best.X < profile.BedWidth / 2 ? 10 : -10);
    }

    private static string F(double v) => TemplateEngine.Format(v);
}
