#!/usr/bin/env python3
"""Generates examples/sample-p1s.gcode: a Bambu-style program (markers, relative E) for trying the app.
A 40x40 mm solid base (5 mm) carries a 24x24 mm tower with 3 walls, 15 % grid infill and a solid
band every 4 mm, 20 mm tall in total, 0.2 mm layers."""
import math, os

out = os.path.join(os.path.dirname(__file__), "..", "examples", "sample-p1s.gcode")
L = []
a = L.append
for h in ["; HEADER_BLOCK_START", "; BambuStudio 02.02.00.85 (sample generated by Gcode Recovery)", "; total layer number: 100", "; HEADER_BLOCK_END"]:
    a(h)
a("; MACHINE_START_GCODE_END")
for c in ["G90", "M83", "M140 S60", "M104 S220", "M190 S60", "M109 S220", "G1 Z5 F600", "G1 X18 Y1 F12000", "G1 Z0.3", "G1 X80 E8 F1500", "M106 P1 S0"]:
    a(c)

W = 0.42
def ext(x0, y0, x1, y1):
    return f"G1 X{x1:.3f} Y{y1:.3f} E{math.hypot(x1-x0, y1-y0)*0.033:.5f}"

def rect_walls(cx, cy, size, walls):
    for w in range(walls):
        s = size / 2 - W / 2 - w * W
        pts = [(cx-s, cy-s), (cx+s, cy-s), (cx+s, cy+s), (cx-s, cy+s), (cx-s, cy-s)]
        a(f"G1 X{pts[0][0]:.3f} Y{pts[0][1]:.3f} F12000")
        a("; FEATURE: Outer wall" if w == 0 else "; FEATURE: Inner wall")
        for p, q in zip(pts, pts[1:]):
            a(ext(*p, *q) + " F3000")

def solid(cx, cy, size, walls):
    s = size / 2 - walls * W
    y = cy - s + W / 2
    d = 1
    a("; FEATURE: Internal solid infill")
    while y <= cy + s - W / 2 + 1e-6:
        x0, x1 = (cx - s, cx + s) if d > 0 else (cx + s, cx - s)
        a(f"G1 X{x0:.3f} Y{y:.3f} F12000")
        a(ext(x0, y, x1, y) + " F4000")
        y += W
        d = -d

def sparse(cx, cy, size, walls, spacing=5.6):
    s = size / 2 - walls * W
    a("; FEATURE: Sparse infill")
    k = -s
    while k <= s:
        a(f"G1 X{cx+k:.3f} Y{cy-s:.3f} F12000"); a(ext(cx+k, cy-s, cx+k, cy+s) + " F6000")
        a(f"G1 X{cx-s:.3f} Y{cy+k:.3f} F12000"); a(ext(cx-s, cy+k, cx+s, cy+k) + " F6000")
        k += spacing

z = 0.0
for layer in range(100):
    z = round(z + 0.2, 3)
    a("; CHANGE_LAYER"); a(f"; Z_HEIGHT: {z}"); a("; LAYER_HEIGHT: 0.2"); a("; LINE_WIDTH: 0.42")
    a("G1 E-.8 F1800")
    a(f"G1 Z{z+0.4:.3f} F600")
    if layer == 1: a("M106 P1 S255")
    a(f"G1 Z{z:.3f}")
    a("G1 E.8 F1800")
    if z <= 5.0:
        rect_walls(128, 128, 40, 3); solid(128, 128, 40, 3)
    else:
        rect_walls(128, 128, 24, 3)
        (solid if (z % 4.0) < 0.81 else sparse)(128, 128, 24, 3)
a("M104 S0"); a("M140 S0"); a("G1 Z30 F600")
a("; CONFIG_BLOCK_START"); a("; initial_layer_print_height = 0.2"); a("; printer_model = Bambu Lab P1S"); a("; CONFIG_BLOCK_END")
with open(out, "w") as f:
    f.write("\n".join(L) + "\n")
print(out, len(L), "lines")
